### ISSUE TITLE
Cal.com Wishlist

### ISSUE THREAD

**Issue by PeerRich** [spacedriveapp/linear-github-sync#1]
moved over to https://github.com/calcom/linear-to-github/issues/1

**Comment by PeerRich** [comment]
@jamiepine @xPolar @Brendonovich does this overlap with some of your ideas? if yes we could split the workload. we're really really excited about this 

cc @sean-brydon

**Comment by xPolar** [comment]
Hey there, I've been wanting to work on syncing labels and labels, didn't have any solid ideas on how to do so other than hard-coded IDs but just a map within the database sounds good. I didn't really think of using OAuth for users so everything is actually created by the users instead of the bots, this is definitely something I'll look into doing. Syncing projects should be relatively easy as well. The only thing I'm confused about is how I would sync milestones?

**Comment by PeerRich** [comment]
moved project over to https://github.com/calcom/linear-to-github/issues/1
